<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Basler.Pylon" Version="1.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.4" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <Protobuf Include="grpc\protos\event.proto" />
    <Protobuf Include="grpc\protos\stream.proto" />
    <Protobuf Include="grpc\protos\stepper.proto" />
  </ItemGroup>
</Project>
